{% if theme.passage_end_tag.enabled %}
<div style="text-align:center;color: #ccc;font-size:14px;">
------ 本文结束 ------</div>
<br/>
<div style="border: 1px solid black">
<div style="margin-left:10px">
<span style="font-weight:blod">版权声明</span>
<img src="http://7xqmjb.com1.z0.glb.clouddn.com/2017020242973cc.png" >
<br/>
<p style="font-size: 10px;line-height: 30px"><a href="https://hackerzzm.github.io" style="color:#258FC6">Hacker_zzm's Notes</a> by <a href="https://hackerzzm.github.io" style="color:#258FC6">Zheming Zou</a> is licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">Creative Commons BY-NC-ND 4.0 International License</a>.<br/>
由<a href="https://hackerzzm.github.io" style="color:#258FC6">邹哲明</a>创作并维护的<a href="https://hackerzzm.github.io" style="color:#258FC6">Hacker_zzm's Notes</a>博客采用<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">创作共用保留署名-非商业-禁止演绎4.0国际许可证</a>。<br/>
本文首发于<a href="https://hackerzzm.github.io" style="color:#258FC6">Hacker_zzm's Notes</a> 博客（ <a href="https://hackerzzm.github.io" style="color:#258FC6">https://hackerzzm.github.io</a> ），版权所有，侵权必究。</p>
</div>
</div>
{% endif %}